Repository automat-ed/simulation, pull requests merged in 2021-03, with the labels that each got.

#39 Update sensor noise models
  lib/sensors/include/sensors/accelerometer.hpp
  lib/sensors/include/sensors/gps.hpp
  lib/sensors/include/sensors/gyro.hpp
  lib/sensors/include/sensors/inertialUnit.hpp
  lib/sensors/include/sensors/lidar.hpp
  lib/sensors/include/sensors/wheelOdometry.hpp
  lib/sensors/src/accelerometer.cpp
  lib/sensors/src/gps.cpp
  lib/sensors/src/gyro.cpp
  lib/sensors/src/inertialUnit.cpp
  lib/sensors/src/lidar.cpp
  lib/sensors/src/wheelOdometry.cpp
  src/full_controller.cpp
Labels: enhancement

#40 Create a proto file
  .gitignore
  protos/StreetSmart.proto
Labels: enhancement

#44 Fix sensors
  lib/sensors/src/accelerometer.cpp
  lib/sensors/src/gyro.cpp
  lib/sensors/src/inertialUnit.cpp
  lib/sensors/src/lidar.cpp
  lib/steering/src/diffSteering.cpp
  protos/StreetSmart.proto
Labels: bug

#45 Prevent instantiation of keyboard controller if param not set
  lib/utils/src/KeyboardController.cpp
  src/full_controller.cpp
Labels: bug

#50 Fix sensors for localization
  lib/sensors/include/sensors/accelerometer.hpp
  lib/sensors/include/sensors/gps.hpp
  lib/sensors/include/sensors/gyro.hpp
  lib/sensors/include/sensors/inertialUnit.hpp
  lib/sensors/src/accelerometer.cpp
  lib/sensors/src/gps.cpp
  lib/sensors/src/gyro.cpp
  lib/sensors/src/inertialUnit.cpp
  lib/sensors/src/lidar.cpp
  lib/steering/include/steering/diffSteering.hpp
  lib/steering/src/diffSteering.cpp
  src/full_controller.cpp
  worlds/curved_path.wbt
  worlds/rectangle.wbt
  worlds/square.wbt
  worlds/straight_line.wbt
  worlds/triangle.wbt
Labels: bug

#49 Add position sensor
  CMakeLists.txt
  lib/sensors/include/sensors/wheelOdom.hpp
  lib/sensors/src/wheelOdom.cpp
  lib/steering/include/steering/diffSteering.hpp
  lib/steering/src/diffSteering.cpp
  protos/StreetSmart.proto
  src/full_controller.cpp
Labels: enhancement

#52 Remove topic parameters
  lib/sensors/include/sensors/accelerometer.hpp
  lib/sensors/include/sensors/gps.hpp
  lib/sensors/include/sensors/gyro.hpp
  lib/sensors/include/sensors/inertialUnit.hpp
  lib/sensors/include/sensors/lidar.hpp
  lib/sensors/include/sensors/wheelOdom.hpp
  lib/sensors/src/accelerometer.cpp
  lib/sensors/src/gps.cpp
  lib/sensors/src/gyro.cpp
  lib/sensors/src/inertialUnit.cpp
  lib/sensors/src/lidar.cpp
  lib/sensors/src/wheelOdom.cpp
  lib/steering/include/steering/diffSteering.hpp
  lib/steering/src/diffSteering.cpp
Labels: enhancement

#51 Updates for Localization
  lib/sensors/src/gps.cpp
  src/full_controller.cpp
  worlds/curved_path.wbt
  worlds/meadows.wbt
  worlds/rectangle.wbt
  worlds/square.wbt
  worlds/straight_line.wbt
  worlds/triangle.wbt
Labels: bug

#47 Add ice
  worlds/curved_path_ice.wbt
  worlds/straight_line_ice.wbt
Labels: enhancement

#53 Add static obstacles to curved path
  worlds/curved_path_obstacles.wbt
Labels: enhancement

#54 Add ground truth pose publisher
  CMakeLists.txt
  lib/utils/include/utils/GroundTruthPose.hpp
  lib/utils/src/GroundTruthPose.cpp
  src/full_controller.cpp
Labels: enhancement

#56 Update README.md
  README.md
  launch/webots.launch
Labels: documentation
