Repository automat-ed/simulation, pull requests merged in 2021-02, with the labels that each got.

#12 Add initial implementation of LiDAR
  CMakeLists.txt
  lib/sensors/include/sensors/lidar.hpp
  lib/sensors/src/lidar.cpp
  package.xml
  src/full_controller.cpp
  worlds/world.wbt
Labels: enhancement

#15 Add GPS Sensor to Simulation
  CMakeLists.txt
  lib/sensors/include/sensors/gps.hpp
  lib/sensors/src/gps.cpp
  src/full_controller.cpp
  worlds/world.wbt
Labels: enhancement

#16 Add IMU sensor to simulation
  CMakeLists.txt
  lib/sensors/include/sensors/inertialUnit.hpp
  lib/sensors/src/inertialUnit.cpp
  src/full_controller.cpp
  worlds/world.wbt
Labels: enhancement

#19 Publish sensor transforms
  CMakeLists.txt
  lib/sensors/include/sensors/gps.hpp
  lib/sensors/include/sensors/inertialUnit.hpp
  lib/sensors/include/sensors/lidar.hpp
  lib/sensors/src/gps.cpp
  lib/sensors/src/inertialUnit.cpp
  lib/sensors/src/lidar.cpp
  package.xml
  src/full_controller.cpp
  worlds/world.wbt
Labels: enhancement

#20 Add MIT license
  LICENSE
Labels: enhancement

#18 Add differential steering
  CMakeLists.txt
  lib/steering/include/steering/diffSteering.hpp
  lib/steering/src/diffSteering.cpp
  src/full_controller.cpp
  worlds/world.wbt
Labels: enhancement

#24 Implemented Accelerometer and corresponding TF
  CMakeLists.txt
  lib/sensors/include/sensors/accelerometer.hpp
  lib/sensors/src/accelerometer.cpp
  src/full_controller.cpp
  worlds/world.wbt
Labels: enhancement

#23 Implemented gyroscope and corresponding TF
  CMakeLists.txt
  lib/sensors/include/sensors/gyro.hpp
  lib/sensors/src/gyro.cpp
  src/full_controller.cpp
  worlds/world.wbt
Labels: enhancement

#25 Add Wheel Odometry to Simulation
  CMakeLists.txt
  lib/sensors/include/sensors/wheelOdometry.hpp
  lib/sensors/src/wheelOdometry.cpp
  lib/steering/include/steering/diffSteering.hpp
  lib/steering/src/diffSteering.cpp
  src/full_controller.cpp
  worlds/world.wbt
Labels: enhancement

#26 Fix CMake Issue
  CMakeLists.txt
Labels: bug

#28 Add CI
  .catkin_lint
  .github/workflows/ci.yaml
Labels: enhancement

#31 Add status badge to README
  README.md
Labels: documentation

#30 Add keyboard controller
  CMakeLists.txt
  lib/utils/include/utils/KeyboardController.hpp
  lib/utils/src/KeyboardController.cpp
  src/full_controller.cpp
Labels: enhancement

#32 Add sensor noise
  lib/sensors/include/sensors/accelerometer.hpp
  lib/sensors/include/sensors/gps.hpp
  lib/sensors/include/sensors/gyro.hpp
  lib/sensors/include/sensors/inertialUnit.hpp
  lib/sensors/include/sensors/lidar.hpp
  lib/sensors/include/sensors/wheelOdometry.hpp
  lib/sensors/src/accelerometer.cpp
  lib/sensors/src/gps.cpp
  lib/sensors/src/gyro.cpp
  lib/sensors/src/inertialUnit.cpp
  lib/sensors/src/lidar.cpp
  lib/sensors/src/wheelOdometry.cpp
Labels: enhancement

#33 Handle KeyboardInterrupt exception
  launch/webots_launcher.py
Labels: bug
